export const POST_RESERVATION = 'POST_RESERVATION';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const ARCHIVE_RESERVATION = 'ARCHIVE_RESERVATION';

export const POST_CUSTOMER = 'POST_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const LOCALE_SET = 'LOCALE_SET';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN_ADMIN = 'SIGN_IN_ADMIN';


