export const POST_RESERVATION = 'POST_RESERVATION';
export const MAIL_RESERVATION = 'MAIL_RESERVATION';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const ARCHIVE_RESERVATION = 'ARCHIVE_RESERVATION';

export const POST_LAST_RESERVATION = 'POST_LAST_RESERVATION';
export const FETCH_LAST_RESERVATIONS = 'FETCH_LAST_RESERVATIONS';
export const DELETE_LAST_RESERVATION = 'DELETE_LAST_RESERVATION';

export const POST_CUSTOMER = 'POST_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const POST_CONTACT = 'POST_CONTACT';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const ARCHIVE_CONTACT = 'ARCHIVE_CONTACT';

export const LOCALE_SET = 'LOCALE_SET';

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const POST_USER = 'POST_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const DELETE_USER = 'DELETE_USER';
export const ADD_CREDIT_TO_USER = 'ADD_CREDIT_TO_USER';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';



